{
 "title": "ECS Dashboard 3.2",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "SHOW TAG VALUES WITH KEY = \"Cluster\""
   },
   {
    "name": "NodeID",
    "label": "NodeID",
    "query": "SHOW TAG VALUES WITH KEY = \"NodeID\""
   }
  ]
 },
 "panels": [
  { "title": "Single Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "transactionReadLatencyCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "transactionWriteLatencyCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "transReadBandwidthCur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionReadBandwidthCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "transWriteBandwidthCur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionWriteBandwidthCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "transReadPerSecondCur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionReadTransactionsPerSecCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "transWritePerSecondCur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionWriteTransactionsPerSecCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Crit Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "alertsNumUnackCritical" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "alertsNumUnackError" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warn Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "alertsNumUnackWarning" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numNodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Maint Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numMaintenanceNodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Bad Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numBadNodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Maint Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numMaintenanceDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Bad Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numBadDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free (TiB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "diskSpaceFreeCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "diskSpaceFreeCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "nodeCpu & nodeMemoryUtilizationCur (mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "nodeCpuUtilizationCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NodeMetrics",
     "select": [
      [
       { "params": [ "nodeCpuUtilizationCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NodeID", "operator": "=~", "value": "/^$NodeID$/" }
     ]
    },
    {
     "alias": "nodeMemoryUtilizationCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NodeMetrics",
     "select": [
      [
       { "params": [ "nodeMemoryUtilizationCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NodeID", "operator": "=~", "value": "/^$NodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "nodeNicUtilizationCurrent (mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "nodeNicReceivedUtilizationCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NodeMetrics",
     "select": [
      [
       {
        "params": [
         "nodeNicReceivedUtilizationCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NodeID", "operator": "=~", "value": "/^$NodeID$/" }
     ]
    },
    {
     "alias": "nodeNicTransmittedUtilizationCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NodeMetrics",
     "select": [
      [
       {
        "params": [
         "nodeNicTransmittedUtilizationCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NodeID", "operator": "=~", "value": "/^$NodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "nodeNicBandwidthCurrent (mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "nodeNicReceivedBandwidthCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NodeMetrics",
     "select": [
      [
       {
        "params": [
         "nodeNicReceivedBandwidthCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NodeID", "operator": "=~", "value": "/^$NodeID$/" }
     ]
    },
    {
     "alias": "nodeNicTransmittedBandwidthCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NodeMetrics",
     "select": [
      [
       {
        "params": [
         "nodeNicTransmittedBandwidthCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NodeID", "operator": "=~", "value": "/^$NodeID$/" }
     ]
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "System Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "diskSpaceAllocatedUserDatacurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedUserDataCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedSystemMetadataCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedSystemMetadataCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedLocalProtectionCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedLocalProtectionCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedGeoCopyCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedGeoCopyCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedGeoCacheCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedGeoCacheCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gcUserPendingCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "gcCombinedPendingCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "diskSpaceAllocatedUserDatacurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedUserDataCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedSystemMetadataCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedSystemMetadataCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedLocalProtectionCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedLocalProtectionCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedGeoCopyCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedGeoCopyCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceAllocatedGeoCacheCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "diskSpaceAllocatedGeoCacheCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gcUserPendingCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "gcUserPendingCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "diskSpaceTotalCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "diskSpaceTotalCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "gcReclaimedCurrent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "gcUserReclaimedCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "gcUserReclaimedCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gcSystemReclaimedCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "gcSystemReclaimedCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "chunksECTotalSealSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "chunksEcCodedTotalSealSize",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "chunksEcCodedTotalSealSizeCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "chunksEcApplicableTotalSealSize",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "chunksEcApplicableTotalSealSizeCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "chunksECRateCurrent",
   "type": "graph",
   "description": "/128 (to MB) / 976.526 (to KiB)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "chunksEcRateCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/128/976.526" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "chunksRepoPendingReplicationTotalSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       {
        "params": [
         "chunksRepoPendingReplicationTotalSize"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "replicationTrafficCurrent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "replicationEgressTrafficCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "replicationEgressTrafficCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "replicationInressTrafficCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "replicationIngressTrafficCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "replicationRpoTimestamp",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 29 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "replicationRpoTimestamp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Transaction - Variety", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "transactionBandwidthCurrent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "transactionReadBandwidthCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionReadBandwidthCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "transactionWriteBandwidthCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionWriteBandwidthCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "transactionLatencyCurrent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "transactionReadLatencyCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "transactionReadLatencyCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "transactionWriteLatencyCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "transactionWriteLatencyCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TransactionBandwidth (Historical @ 1 hr)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "transactionReadBandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "transactionReadBandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "transactionWriteBandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       { "params": [ "transactionWriteBandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "transactionPerSecCurrent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "transactionReadPerSecCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionReadTransactionsPerSecCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "transactionWritePerSecCurrent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneMetrics",
     "select": [
      [
       {
        "params": [
         "transactionWriteTransactionsPerSecCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TransactionReadBandwidthSummary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "transReadBandwithSumAvg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneSummary",
     "select": [
      [
       {
        "params": [
         "transactionReadBandwidthSummaryAvg"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "transReadBandwithSumMax",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneSummary",
     "select": [
      [
       {
        "params": [
         "transactionReadBandwidthSummaryMax"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "transReadBandwithSumMin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LocalZoneSummary",
     "select": [
      [
       {
        "params": [
         "transactionReadBandwidthSummaryMin"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}